import java.awt.CardLayout;

import javax.swing.JFrame;
import javax.swing.JPanel;


/**
 *
 * @author proga_000
 */
public class HomePage extends javax.swing.JPanel {
    
    //EntityManagerFactory emfactory = Persistence.createEntityManagerFactory("PersistenceUnit");
    //EntityManager entitymanager = emfactory.createEntityManager();
    JPanel cards;
    CardLayout cl;
    String username = "";
    JFrame win;
    BasicLessonAlphabet basicLA;

    /**
     * Creates new form HomePage1
     */
    public HomePage(JPanel c,CardLayout cardlayout, JFrame window) {
    	cards =c;
    	cl = cardlayout;
    	win = window;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        studentInfoButton = new javax.swing.JButton();
        startBasicButton = new javax.swing.JButton();
        startAdvButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Student's First and Last Name");

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        studentInfoButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        studentInfoButton.setText("Student Info");
        studentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoButtonActionPerformed(evt);
            }
        });

        startBasicButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        startBasicButton.setText("Start Basic Level");
        startBasicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBasicButtonActionPerformed(evt);
            }
        });

        startAdvButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        startAdvButton.setText("Start Advanced Level");
        startAdvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAdvButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField))
                    .addComponent(studentInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startBasicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startAdvButton, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(81, 81, 81)
                .addComponent(studentInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(startBasicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(startAdvButton, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>                        

    private void studentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void startBasicButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        username = nameTextField.getText();
    	
    	//Query query1 = entitymanager.createQuery("SELECT s.name FROM student_info s WHERE s.name=:sname");
    	/*query1.setParameter("sname", username);
    	try{
    		String result = (String) query1.getSingleResult();
    	}
    	catch(NoResultException e){
    		//student is not already in the database
    		EntityTransaction transaction = entitymanager.getTransaction();
    		//update database to include student
    		StudentInfo newStudent = new StudentInfo();
    		newStudent.setStudentName(username);
    		newStudent.setBasicLetterGameScore(0);
    		newStudent.setBasicNumberGameScore(0);
    		newStudent.setBasicAnimalGameScore(0);
    		newStudent.setAdvLetterGameScore(0);
    		newStudent.setAdvCountingGameScore(0);
    		transaction.begin();
    		entitymanager.persist(newStudent);
    		transaction.commit();
    	}
    	*/
    	//code to transition to starting the basic lesson
        //cl.show(cards, "BLALPHABET");
        //CardLayout cardlayout = (CardLayout) win.getLayout();
        cards.add(new BasicLessonAlphabet(win,cards,cl), "Basic Lesson Alphabet");
        cl.show(cards, "Basic Lesson Alphabet");
        //cl.next(cards);
        //basicLA.play(win);
        
        
       
    }                                                

    private void startAdvButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        username = nameTextField.getText();
    	
    	//Query query1 = entitymanager.createQuery("SELECT s.name FROM student_info s WHERE s.name=:sname");
    	//query1.setParameter("sname", username);
    	/*try{
    		String result = (String) query1.getSingleResult();
    	}
    	catch(NoResultException e){
    		//student is not already in the database
    		EntityTransaction transaction = entitymanager.getTransaction();
    		//update database to include student
    		StudentInfo newStudent = new StudentInfo();
    		newStudent.setStudentName(username);
    		newStudent.setBasicLetterGameScore(0);
    		newStudent.setBasicNumberGameScore(0);
    		newStudent.setBasicAnimalGameScore(0);
    		newStudent.setAdvLetterGameScore(0);
    		newStudent.setAdvCountingGameScore(0);
    		transaction.begin();
    		entitymanager.persist(newStudent);
    		transaction.commit();
    		
    	}
    	*/
    	//code to transition to start the advanced lesson 
    }                                              


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton startAdvButton;
    private javax.swing.JButton startBasicButton;
    private javax.swing.JButton studentInfoButton;
    // End of variables declaration                   
}